--- !ditz.rubyforge.org,2008-03-06/project 
name: GNU Emacs Ditz mode
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: ditz-mode
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-03-17 10:14:28.019849 Z
    - Glenn Hutchings <zondo42@googlemail.com>
    - created
    - ""
